### ISSUE TITLE
Numbers not (always) fully displayed on Statistics tab

### ISSUE THREAD

**Issue by LeonTQS** [asreview/asreview#238] opened 2020-04-15 14:58 UTC
See attachment
<img width="186" alt="Numbers not fully displayed" src="https://user-images.githubusercontent.com/63716760/79352525-43c47280-7f3a-11ea-9ac5-97e4296dbc95.PNG">

**Comment by J535D165** [comment] 2020-04-15 18:58
This is a very unlikely situation in which there are only relevant publications. It tried to reproduce this, but I failed to do so because of an error with the pool. Although this is highly unlikely, we should try to prevent this situation.

**Comment by LeonTQS** [comment] 2020-04-16 11:16
@qubixes Also happens with 1 included (step 3) and 5 irrelevant (step 4), see attachment.
<img width="178" alt="Numbers not fully displayed II" src="https://user-images.githubusercontent.com/63716760/79449977-7c208b00-7fe4-11ea-9909-dd09ce45e9f8.PNG">

**Comment by J535D165** [comment] 2020-04-16 11:19
Oke, good to know. I will try to fix this.

**Comment by Rensvandeschoot** [comment] 2020-07-31 06:38
@terrymyc is this issue also solved in the upcomming release??

**Comment by J535D165** [comment] 2020-07-31 06:59
No, this issue is still open.

**Comment by terrymyc** [comment] 2020-07-31 07:48
In fact, I noticed and solved this issue. @J535D165 @Rensvandeschoot 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/17449217/89012477-9a4f9400-d312-11ea-9be6-e4ae84cd5c98.png">
<img width="242" alt="image" src="https://user-images.githubusercontent.com/17449217/89012655-cb2fc900-d312-11ea-92fb-e88bc94f79fd.png">

**Comment by J535D165** [comment] 2020-07-31 09:08
Nice! Closing this issue.

**Closed by J535D165** 2020-07-31 09:08 UTC
Labels: bug
