### ISSUE TITLE
Add progress bar to simulation runs

### ISSUE THREAD

**Issue by pablov-1995** [asreview/asreview#623] opened 2021-06-03 18:31 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**
A simulation run can often take many hours. It would be nice for the people using ASReview simulation to know how many papers are left to be screened.

**Describe the solution you'd like**
Two TQDM-like progress bars that show:

- How many papers have been screened over the total number of papers in the dataset.
- How many relevant papers have been found over the total number of relevant papers in the dataset.

**Describe alternatives you've considered**
I have not really considered other alternatives. There could also be an output message in the simulation every time a paper is screened, and the number of papers left to be screened (same with the relevant papers: message every time a relevant paper is found, and the number of relevant papers yet to be found), but I don't like it as much.

**Teachability, Documentation, Adoption, Migration Strategy**
I would add a parameter, `progress-bar`, that is false by default and true if the user wants to see the progress of the simulation.

Maybe with screenshot or design?

![prog_ast](https://user-images.githubusercontent.com/57364973/120694487-90566e80-c4aa-11eb-909e-bc3ff2628f01.png)

**Comment by pablov-1995** [comment] 2021-06-04 09:52
Since ASReview is written in Python, maybe it would even be possible to find some hacky workaround TQDM to do this, so it is displayed on the console?

**Comment by J535D165** [comment] 2021-06-04 12:34
Duplicate of #345. 

Thanks for the feature request and idea for improvement. I like the idea of the two progress bars in the screenshot, is this an attempt to implement this, or an example? I think TQDM offers a lot of options to implement this. Let's continue the discussion in the other issue.

**Closed by J535D165** 2021-06-04 12:34 UTC
