### ISSUE TITLE
Count priors since last relevant and first article shown

### ISSUE THREAD

**Issue by Morle2104** [asreview/asreview#1923] opened 2024-11-11 15:15 UTC
Dear all, 
To switch from double to single screening, we merged the xlsx ASReview output files in Excel, and dealt with conflicting labels. Now I uploaded an Excel file with the column label_included and created a new project. ASReview recognizes all labels correctly as prior knowledge, however there are two strange things that happened. 
Number 1, in Analytics it gives the number 1.599 for 'irrelevant records since last relevant', but I have no idea where this number comes from. I uploaded the Excel and made a new project and have not started screening again. In the Excel with which I created the new project, there are only columns related to the articles (pubmed id, abstract, title etc.) and the label_included column. However, it is still the structure of the Excel output file of ASReview in the sense that all as relevant labelled articles are at the top and all as irrelevant at the bottom. 
The second strange thing is that I uploaded the same Excel sheet a couple of times, and everytime it gives me a different first abstract to screen. However, given that I chose query strategy 'maximum', it should always be the same abstract based on my understanding. 
I checked the Excel sheet and tried to modify some things that I thought caused the problem (e.g., I took the record_id column out), but that did not solve it.

_Originally posted by @Morle2104 in https://github.com/asreview/asreview/discussions/1912#discussioncomment-11215847_

**Comment by Rensvandeschoot** [comment] 2024-11-12 08:09
duplicate of https://github.com/asreview/asreview/discussions/1924

**Closed by Rensvandeschoot** 2024-11-12 08:09 UTC
